### PR TITLE
Add “Not npm install query-string !!!!!” to the readme!

### PR DESCRIPTION
**Pull request by yinxulai**
ref：https://github.com/sindresorhus/query-string/blob/main/readme.md#install

image

### CODE REVIEW

**Comment by yinxulai** [comment]
hahahah

image

**Comment by yinxulai** [comment]
@Gozala

**Review by medikoo — COMMENTED** [review]
Thanks @yinxulai, still I think it's not needed in context of this repository.

It's a `querystring` that's typically used. In `query-string` package there's such note, to ensure user do not fall into trap of using common name (which is `querystring`). Here there's no such case

**Comment by yinxulai** [comment]
I thought it was an interesting interaction.

**Comment by medikoo** [comment]
@yinxulai I think it's best to keep documentation minimal. We may add a lot of potentially valuable _hints_, but if they do not help anyone, they make reading documentation just harder, as it's just noise user has to get through.

In this specific case, I think users do not have a problem installing correct package, so I don't think there's a need to add such note.

**Comment by yinxulai** [comment]
That's good.

**Pull request closed without merging**
